spring:
  application:
    name: product-service
  data:
    mongodb:
      host: mongo
      port: 27017
      database: productDb
      repositories:
        enable: true

server:
  port: 6161

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: ${EUREKA_URI:http://eureka:8761/eureka}
  instance:
    prefer-ip-address: true

error:
  whitelabel:
    enabled: false

security:
  oauth2:
    resource:
      user-info-uri: http://auth:8088/user