spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productDb
      repositories:
        enable: true

server:
  port: 6161

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

error:
  whitelabel:
    enabled: false